# Generated by Django 4.2.5 on 2023-10-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagem/')),
                ('Banner', models.ImageField(upload_to='imagem/')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
