# Generated by Django 4.2.5 on 2023-10-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(null=True, upload_to='cliente_fotos/'),
        ),
    ]
