# Generated by Django 4.2.5 on 2023-10-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_profissional_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
