# Generated by Django 4.2.5 on 2023-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_profissional_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='Banner',
            field=models.ImageField(upload_to='imagem/banner'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(max_length=60),
        ),
    ]
