# Generated by Django 4.2.5 on 2023-10-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_profissional_banner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profissional',
        ),
    ]
