# Generated by Django 4.2.5 on 2023-10-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_delete_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagem/')),
                ('Banner', models.ImageField(upload_to='imagem/banner')),
            ],
        ),
    ]
