# Generated by Django 4.2.5 on 2023-10-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
