# Generated by Django 4.2.5 on 2023-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_profissional_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='banner',
            field=models.ImageField(default='Não há banners definidos', upload_to='imagem/banner/'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(default='Não há endereço definido', max_length=60),
        ),
    ]
